=== RunOnceEx/esdk_Cgw/self_dev/eSDK_eLTE_SDK/debug/eLTE_NativeService/conf/deploy_policy.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
file      : \code\src\platform\modules\sca\deploy_policy.xsd
install   : \install\conf\deploy_policy.xsd
author    : ZhongWei
created   : 2012/10/26 13:30
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:svcmgr="http://www.td-tech.com/ubp/platform/svcmgr/xml"
            targetNamespace="http://www.td-tech.com/ubp/platform/svcmgr/xml">

  <xsd:complexType name="CoreInfo">
    <xsd:attribute name="core_count" type="xsd:string" use="required"/>
    <xsd:attribute name="value" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="Service">
  	<xsd:sequence>
      <xsd:element name="CoreInfo" type="svcmgr:CoreInfo" maxOccurs="unbounded" minOccurs="0"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>  
  
  <xsd:complexType name="ServiceMode">
  	<xsd:sequence>
      <xsd:element name="Service" type="svcmgr:Service" maxOccurs="unbounded" minOccurs="0"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>    
  </xsd:complexType>              

  <xsd:complexType name="ServiceModeInfo">
    <xsd:sequence>
      <xsd:element name="ServiceMode" type="svcmgr:ServiceMode" maxOccurs="unbounded"/>
    </xsd:sequence>    
  </xsd:complexType>            
  
  <xsd:complexType name="ServiceTypeA">
    <xsd:attribute name="type" type="xsd:string" use="required"/>
    <xsd:attribute name="defaultname" type="xsd:string" use="required"/>
    <xsd:attribute name="svc_mode" type="xsd:string" use="required"/>
    <xsd:attribute name="pubport" type="xsd:int" use="required"/>
    <xsd:attribute name="dealport" type="xsd:int" use="required"/>
    <xsd:attribute name="ip_type" type="xsd:int" use="required"/>
    <xsd:attribute name="cpu_type" type="xsd:int" use="required"/>
  </xsd:complexType> 

  <xsd:complexType name="ServiceProxy">
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="proxy_ip" type="xsd:string" use="required"/>
  </xsd:complexType> 

  <xsd:complexType name="ProxyPolicy">
    <xsd:sequence>
      <xsd:element name="ServiceProxy" type="svcmgr:ServiceProxy" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="default_ip" type="xsd:string" use="required"/>
    <xsd:attribute name="active_subpolicy" type="xsd:boolean" />  
  </xsd:complexType>  

  <xsd:complexType name="ServiceTypeInfo">
    <xsd:sequence>
      <xsd:element name="ServiceTypeA" type="svcmgr:ServiceTypeA" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="port_offset" type="xsd:int" use="required"/>
    <xsd:attribute name="broker_dealport" type="xsd:int" use="required"/>
    <xsd:attribute name="broker_pubport" type="xsd:int" use="required"/>
  </xsd:complexType>  

  <xsd:complexType name="HostCfg">
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="value" type="xsd:string" use="required"/>
  </xsd:complexType>
    
  <xsd:complexType name="HostInfo">
    <xsd:sequence>
      <xsd:element name="HostCfg" type="svcmgr:HostCfg" maxOccurs="unbounded"/>
    </xsd:sequence> 
  </xsd:complexType>
  
  <xsd:complexType name="ServicePolicy">
  	   <xsd:sequence>
          <xsd:element name="HostInfo" type="svcmgr:HostInfo" />
          <xsd:element name="ProxyPolicy" type="svcmgr:ProxyPolicy" />
          <xsd:element name="ServiceTypeInfo" type="svcmgr:ServiceTypeInfo" />
          <xsd:element name="ServiceModeInfo" type="svcmgr:ServiceModeInfo" />
       </xsd:sequence>
  </xsd:complexType>
  
  <xsd:element name="ServicePolicy" type="svcmgr:ServicePolicy"/>
</xsd:schema>

=== RunOnceEx/esdk_Cgw/self_dev/eSDK_eLTE_SDK/debug/eLTE_NativeService/conf/dc/deploy_policy.xml
<?xml version="1.0" encoding="utf-8"?>
<svcmgr:ServicePolicy xmlns:svcmgr="http://www.td-tech.com/ubp/platform/svcmgr/xml"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:schemaLocation="http://www.td-tech.com/ubp/platform/svcmgr/xml deploy_policy.xsd">

  <HostInfo>
    <HostCfg name="init_local_service" value="false"/>   	
    <HostCfg name="host_name"
             value="$ubp_local_host_name" />
    <HostCfg name="service_mode"
             value="MDC" />
    <HostCfg name="cpu_cores"
             value="16" />
    <HostCfg name="om_ip"
             value="$ubp_local_ip" />
    <HostCfg name="med_ip"
             value="$ubp_local_ip" />
    <HostCfg name="signal_ip"
             value="$ubp_local_ip" />	     
    <HostCfg name="master_ip"
             value="" />
    <HostCfg name="veristas_mode"
             value="NO_SET" />
    <HostCfg name="bcc_ip"
             value="" />
    <!--HostCfg name="dev_db_ip" value="10.121.87.8"/-->
  </HostInfo>
  
  <!--兼容需要：非调度机服务或者2.1低版本调度机服务 -->
  <ProxyPolicy default_ip="signal_ip" active_subpolicy="false">
      <ServiceProxy name="ubp_ue" proxy_ip="NON_MDC"/>
      <ServiceProxy name="ubp_afee" proxy_ip="NON_MDC"/>
  </ProxyPolicy>	
  <ServiceTypeInfo port_offset="0" broker_dealport="22999" broker_pubport="22998">

    <ServiceTypeA type="daem_agent"
                  defaultname="ubp_daem"
                  svc_mode="ipc"
                  pubport="20001"
                  dealport="20002"
                  ip_type="0" 
                  cpu_type="0" />
    <ServiceTypeA type="mq_broker_agent"    	            
                  defaultname="ubp_mq_broker"
                  svc_mode="ipc"
                  pubport="20015"
                  dealport="20016"
                  ip_type="0"
                  cpu_type="0" />                  
    <ServiceTypeA type="cm_agent"
                  defaultname="ubp_cm"
                  svc_mode="ipc"
                  pubport="20100"
                  dealport="20005"
                  ip_type="0"
                  cpu_type="0" />
    <ServiceTypeA type="fm_agent"
                  defaultname="ubp_fm"
                  svc_mode="ipc"
                  pubport="20007"
                  dealport="20008"
                  ip_type="0"
                  cpu_type="0" />
    <ServiceTypeA type="lm_agent"
                  defaultname="ubp_lm"
                  svc_mode="ipc"
                  pubport="20010"
                  dealport="20011"
                  ip_type="0"
                  cpu_type="0" />
    <ServiceTypeA type="mon_agent"
                  defaultname="ubp_monitor"
                  svc_mode="ipc"
                  pubport="20013"
                  dealport="20014"
                  ip_type="0"
                  cpu_type="0" />
    <ServiceTypeA type="maintain_agent"
                  defaultname="ubp_maintain"
                  svc_mode="ipc"
                  pubport="20017"
                  dealport="20018"
                  ip_type="0"
                  cpu_type="0" />
    <ServiceTypeA type="bcc_agent"
                  defaultname="ubp_bcc"
                  svc_mode="ipc"
                  pubport="22001"
                  dealport="22002"
                  ip_type="2"
                  cpu_type="0" />
    <ServiceTypeA type="bdc_agent"
                  defaultname="ubp_bdc01"
                  svc_mode="ipc"
                  pubport="22004"
                  dealport="22005"
                  ip_type="2"
                  cpu_type="1" />
    <ServiceTypeA type="bdc_agent"
                  defaultname="ubp_bdc02"
                  svc_mode="ipc"
                  pubport="22006"
                  dealport="22007"
                  ip_type="2"
                  cpu_type="1" />
    <ServiceTypeA type="bdc_agent"
                  defaultname="ubp_bdc03"
                  svc_mode="ipc"
                  pubport="22008"
                  dealport="22009"
                  ip_type="2"
                  cpu_type="1" />
    <ServiceTypeA type="bdc_agent"
                  defaultname="ubp_bdc04"
                  svc_mode="ipc"
                  pubport="22010"
                  dealport="22011"
                  ip_type="2"
                  cpu_type="1" />
    <ServiceTypeA type="bdc_agent"
                  defaultname="ubp_bdc05"
                  svc_mode="ipc"
                  pubport="22012"
                  dealport="22013"
                  ip_type="2"
                  cpu_type="1" />
    <ServiceTypeA type="bdc_agent"
                  defaultname="ubp_bdc06"
                  svc_mode="ipc"
                  pubport="22014"
                  dealport="22015"
                  ip_type="2"
                  cpu_type="1" />
    <ServiceTypeA type="dec_vgw_agent"
                  defaultname="ubp_dec_vgw"
                  svc_mode="ipc"
                  pubport="22022"
                  dealport="22023"
                  ip_type="2"
                  cpu_type="0" />
    <ServiceTypeA type="diam_agent"
                  defaultname="ubp_diam"
                  svc_mode="ipc"
                  pubport="22024"
                  dealport="22025"
                  ip_type="2"
                  cpu_type="0" />
    <ServiceTypeA type="gis_agent"
                  defaultname="ubp_gis"
                  svc_mode="ipc"
                  pubport="22028"
                  dealport="22029"
                  ip_type="2"
                  cpu_type="0" />
    <ServiceTypeA type="mrs_mgr_agent"
                  defaultname="ubp_mrs_mgr"
                  svc_mode="ipc"
                  pubport="22049"
                  dealport="22050"
                  ip_type="2"
                  cpu_type="0" />
    <ServiceTypeA type="lic_man_agent"
                  defaultname="ubp_lic_man"
                  svc_mode="ipc"
                  pubport="22057"
                  dealport="22058"
                  ip_type="0"
                  cpu_type="0" />
    <ServiceTypeA type="mrs_vgw_agent"
                  defaultname="ubp_mrs_vgw"
                  svc_mode="ipc"
                  pubport="22060"
                  dealport="22061"
                  ip_type="2"
                  cpu_type="0" />
    <ServiceTypeA type="sds_adapter_agent"
                  defaultname="ubp_sds_adapter"
                  svc_mode="ipc"
                  pubport="22063"
                  dealport="22064"
                  ip_type="2"
                  cpu_type="1" />
    <ServiceTypeA type="mrs_node_mgr_agent"
                  defaultname="ubp_mrs_node_mgr"
                  svc_mode="ipc"
                  pubport="22066"
                  dealport="22067"
                  ip_type="2"
                  cpu_type="0" />
    <ServiceTypeA type="mrs_rec_man_agent"
                  defaultname="ubp_mrs_rec_man"
                  svc_mode="ipc"
                  pubport="22069"
                  dealport="22070"
                  ip_type="2"
                  cpu_type="0" />
    <ServiceTypeA type="mrs_rec_sinker_agent"
                  defaultname="ubp_mrs_rec_sinker"
                  svc_mode="ipc"
                  pubport="22072"
                  dealport="22073"
                  ip_type="2"
                  cpu_type="1" />
	<ServiceTypeA type="mrs_ivs_agent"
                  defaultname="ubp_mrs_ivs"
                  svc_mode="ipc"
                  pubport="22074"
                  dealport="22075"
                  ip_type="2"
                  cpu_type="0" />
    <ServiceTypeA type="ue_agent"
                  defaultname="ubp_ue"
                  svc_mode="tcp"
                  pubport="0"
                  dealport="9900"
                  ip_type="0"
                  cpu_type="0" />
    <ServiceTypeA type="afee_agent"
                  defaultname="ubp_afee"
                  svc_mode="tcp"
                  pubport="0"
                  dealport="15003"
                  ip_type="0"
                  cpu_type="0" />
    <ServiceTypeA type="itf_mgr_agent"
                  defaultname="ubp_itf_manager"
                  svc_mode="ipc"
                  pubport="22096"
                  dealport="22097"
                  ip_type="2"
                  cpu_type="0" />
    <ServiceTypeA type="sdk_frm_agent"
                  defaultname="ubp_sdk_agent_01"
                  svc_mode="ipc"
                  pubport="22100"
                  dealport="22101"
                  ip_type="2"
                  cpu_type="0" />
    <ServiceTypeA type="sdk_frm_agent"
                  defaultname="ubp_sdk_agent_02"
                  svc_mode="ipc"
                  pubport="22102"
                  dealport="22103"
                  ip_type="2"
                  cpu_type="0" />
    <ServiceTypeA type="sdk_frm_agent"
                  defaultname="ubp_sdk_agent_03"
                  svc_mode="ipc"
                  pubport="22104"
                  dealport="22105"
                  ip_type="2"
                  cpu_type="0" />
    <ServiceTypeA type="sdk_frm_agent"
                  defaultname="ubp_sdk_agent_04"
                  svc_mode="ipc"
                  pubport="22106"
                  dealport="22107"
                  ip_type="2"
                  cpu_type="0" />
    <ServiceTypeA type="sdk_frm_agent"
                  defaultname="ubp_sdk_agent_05"
                  svc_mode="ipc"
                  pubport="22108"
                  dealport="22109"
                  ip_type="2"
                  cpu_type="0" />
    <ServiceTypeA type="sdk_frm_agent"
                  defaultname="ubp_sdk_agent_06"
                  svc_mode="ipc"
                  pubport="22110"
                  dealport="22111"
                  ip_type="2"
                  cpu_type="0" />
    <ServiceTypeA type="sdk_frm_agent"
                  defaultname="ubp_sdk_agent_07"
                  svc_mode="ipc"
                  pubport="22112"
                  dealport="22113"
